---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r echo=TRUE}
filename <- "activity.csv"
if(!file.exists(filename)) {
        unzip("activity.zip")
        }
data <- read.csv(filename)
data$date <- as.Date(data$date)
data$hour <- data$interval %/% 100
data$minute <- data$interval %% 100

library(lubridate)
data$time <- hm(paste0(data$hour, ":", data$minute))
data$DateTime <- ymd_hm(paste0(data$date, " ", data$hour, ":", data$minute))
```

## What is mean total number of steps taken per day?
```{r echo=TRUE}
steps <- xtabs(steps ~ date, data)
hist(steps)
smean <- mean(steps)
smedian <- median(steps)
```
The mean and median of the total number of steps taken per day are `r smean` and `r smedian`, respectively.

## What is the average daily activity pattern?
```{r echo=TRUE}
mean_steps <- xtabs(steps ~ interval, data)
#plot()
```

## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
